rootProject.name = "BudgetManager"

include(":app")
include(":core-common")
include(":core-ui")
include(":core-database")
include(":core-network")
include(":feature-dashboard")
include(":feature-transactions")
include(":feature-budget")
include(":feature-creditcards")
include(":feature-expensesplit")
include(":feature-settings")
include(":domain")
include(":data")
